default:
  image: node:20.0

deploy_preview:
  stage: deploy
  tags:
    - vercel
    - macos
  except:
    - main
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm use 20
    - node -v
    - npm -v
    - npm install -g vercel
  script:
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN ./monitoring-app
    - vercel build --token=$VERCEL_TOKEN ./monitoring-app
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN ./monitoring-app

deploy_production:
  stage: deploy
  tags:
    - vercel
    - macos
  only:
    - main
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm use 20
    - node -v
    - npm -v
    - npm install -g vercel
  script:
    # - vercel pull --yes --environment=production --token=$VERCEL_TOKEN ./monitoring-app
    # - vercel build --prod --token=$VERCEL_TOKEN ./monitoring-app
    - vercel deploy --prod --token=$VERCEL_TOKEN ./monitoring-app
