default:
  image: node:20.0

deploy_preview:
  stage: deploy
  tags:
    - vercel
    - macos
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      changes:
        - monitoring-app/**
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm use 20
    - node -v
    - npm -v
    - npm install -g vercel
  script:
    - vercel deploy --token=$VERCEL_TOKEN ./monitoring-app

deploy_production:
  stage: deploy
  tags:
    - vercel
    - macos
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - monitoring-app/**
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm use 20
    - node -v
    - npm -v
    - npm install -g vercel
  script:
    - vercel deploy --prod --token=$VERCEL_TOKEN ./monitoring-app
