default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN ./monitoring-app
    - vercel build --token=$VERCEL_TOKEN ./monitoring-app
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN ./monitoring-app

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN ./monitoring-app
    - vercel build --prod --token=$VERCEL_TOKEN ./monitoring-app
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN ./monitoring-app
