default:
  image: node:20.0

deploy_preview:
  stage: deploy
  tags:
    - vercel
    - macos
  except:
    - main
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm use node
    - node -v
    - npm -v
  script:
    - npx vercel
    - cd ./monitoring-app
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  tags:
    - vercel
    - macos
  only:
    - main
  before_script:
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm use node
    - node -v
    - npm -v
  script:
    - npx vercel
    - cd ./monitoring-app
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
